### ISSUE TITLE
Failing to download the generated JSON key 

### ISSUE THREAD

**Issue by mytk2** [google/create-service-account#5]
The script works fine and it successfully creates the key `Filename: gwm-service-account-key-YYYY-MM-DD-XX-XX-XX.json`, but the generated JSON key cannot be downloaded. 

When I click the Download in the Download File pop up, it fails due to "No such file".

**Workaround**
- See the name of the file
`ls -l /tmp`
- Open the file and copy and paste the text. 
`cat /tmp/filename.json`

**Comment by ssahni** [comment]
Fixed in https://github.com/google/create-service-account/commit/b55094966f23350c1f711468fbe6ea9e0dfce148
